import { AlertTriangle, Info, Minus, TrendingDown, TrendingUp } from "lucide-react";
import type { AnalyzeResponse } from "../../services/apiClient";

// `sections` is itself optional on AnalyzeResponse, so both levels need
// unwrapping before indexing.
type VentureScore = NonNullable<NonNullable<AnalyzeResponse["sections"]>["venture_score"]>;

/**
 * Surfaces the trained VentureFlow Score model's output.
 *
 * The design goal is narrow and deliberate: a sceptical investor should be
 * able to tell, without reading documentation, how much of this number is
 * evidence about *this* company versus a population prior, and how much the
 * model itself thinks it knows. So the point estimate is never shown alone --
 * it always appears with its uncertainty band, its confidence label, and the
 * split between the model's prior and this report's evidence adjustment.
 *
 * Showing a bare "57/100" would be the same failure mode as the hand-tuned
 * formula this model replaced: a confident-looking number with nothing behind
 * it that a reader can interrogate.
 */

const CONFIDENCE_STYLES = {
  high: { fg: "#0EA66A", bg: "rgba(14,166,106,0.08)", bd: "rgba(14,166,106,0.24)", label: "High confidence" },
  medium: { fg: "#C47A0A", bg: "rgba(196,122,10,0.08)", bd: "rgba(196,122,10,0.24)", label: "Medium confidence" },
  low: { fg: "#D93025", bg: "rgba(217,48,37,0.07)", bd: "rgba(217,48,37,0.22)", label: "Low confidence" },
} as const;

const bandFor = (score: number) =>
  score >= 65 ? { fg: "#0EA66A", text: "Above comparable base rate" }
    : score >= 45 ? { fg: "#C47A0A", text: "Near comparable base rate" }
      : { fg: "#D93025", text: "Below comparable base rate" };

export default function VentureScorePanel({
  data,
  reportedScore,
  incompleteAnalysis,
}: {
  data?: VentureScore;
  /** The report's headline final_score, which may have been capped. */
  reportedScore?: number;
  /** True when verification was too thin for the report to stand on. */
  incompleteAnalysis?: boolean;
}) {
  // The model is an optional signal by contract -- absent model file, absent
  // section, or an explicit availability failure all render the same honest
  // fallback rather than an empty space or a fabricated score.
  if (!data || !data.available || typeof data.venture_score !== "number") {
    return (
      <section className="vs-card vs-card-muted" aria-labelledby="vs-heading">
        <h2 id="vs-heading" className="vs-eyebrow">VentureFlow Score</h2>
        <div className="vs-unavailable">
          <AlertTriangle size={14} aria-hidden="true" />
          <div>
            <strong>Model score unavailable for this report.</strong>
            <p>{data?.reason || "The trained model could not be loaded, so this report used the fallback scoring formula."}</p>
          </div>
        </div>
      </section>
    );
  }

  const score = data.venture_score;
  const confidence = CONFIDENCE_STYLES[data.confidence ?? "low"];
  const baseRate = Math.round((data.base_rate ?? 0) * 100);
  const coverage = Math.round((data.feature_coverage ?? 0) * 100);
  const modelOnly = data.model_only_score;
  const penaltyPoints = Math.round((data.evidence_penalty ?? 0) * 100);
  const lift = score - baseRate;
  const LiftIcon = lift > 2 ? TrendingUp : lift < -2 ? TrendingDown : Minus;

  return (
    <section className="vs-card" aria-labelledby="vs-heading">
      <div className="vs-head">
        <div>
          <h2 id="vs-heading" className="vs-eyebrow">VentureFlow Score</h2>
          <p className="vs-sub">Trained model · not generated by the language model</p>
        </div>
        <span
          className="vs-conf"
          style={{ color: confidence.fg, background: confidence.bg, borderColor: confidence.bd }}
        >
          {confidence.label}
        </span>
      </div>

      {/* The headline number, its interval and its band live in VerdictHero at
          the top of the page now. Repeating them here put "48 / likely 40-57 /
          near comparable base rate" on screen twice, a few inches apart, which
          reads as two findings rather than one and flattens the hierarchy the
          hero exists to create.
          What is left is the part the hero deliberately does NOT carry: how the
          number was arrived at. */}
      <p className="vs-explains">
        The score above, explained. It is a model prior for a company with these
        characteristics, adjusted down by what this particular report found.
      </p>

      {/* Where the number came from: prior vs. this report's own evidence. */}
      {typeof modelOnly === "number" && (
        <div className="vs-breakdown">
          <div className="vs-bd-row">
            <span>Model prior (company characteristics)</span>
            <strong>{modelOnly}</strong>
          </div>
          <div className="vs-bd-row">
            <span>Evidence from this report (claims, risk, financials)</span>
            <strong style={{ color: penaltyPoints > 0 ? "#D93025" : "#0EA66A" }}>
              {penaltyPoints > 0 ? `−${penaltyPoints}` : "0"}
            </strong>
          </div>
          <div className="vs-bd-row vs-bd-total">
            <span>VentureFlow Score</span>
            <strong style={{ color: bandFor(score).fg }}>{score}</strong>
          </div>
        </div>
      )}

      <div className="vs-stats">
        <div className="vs-stat">
          <span className="vs-stat-k">vs. base rate</span>
          <span className="vs-stat-v" style={{ color: bandFor(score).fg }}>
            <LiftIcon size={12} aria-hidden="true" /> {lift > 0 ? "+" : ""}{lift} pts
          </span>
        </div>
        <div className="vs-stat">
          <span className="vs-stat-k">Input coverage</span>
          <span className="vs-stat-v">{coverage}% observed</span>
        </div>
        <div className="vs-stat">
          <span className="vs-stat-k">Model agreement</span>
          <span className="vs-stat-v">±{Math.round((data.ensemble_std ?? 0) * 100)} pts</span>
        </div>
      </div>

      {/* When the pipeline caps the headline score because verification was
          too thin, the page would otherwise show the model's number here and
          a different, lower number in the stat card below it, with nothing
          explaining the gap. Two unexplained scores on one page is worse than
          either score alone, so the cap is stated explicitly wherever it
          applies. */}
      {incompleteAnalysis && typeof reportedScore === "number" && reportedScore !== score && (
        <p className="vs-warn">
          <AlertTriangle size={12} aria-hidden="true" />
          <span>
            The headline score for this report is capped at <strong>{reportedScore}</strong>,
            not {score}. Verification was too incomplete to stand behind the model's estimate —
            the model only saw company characteristics, and the claims needed to corroborate
            them could not be checked.
          </span>
        </p>
      )}

      {/* Low confidence is stated as an instruction, not decoration. */}
      {data.confidence === "low" && (
        <p className="vs-warn">
          <AlertTriangle size={12} aria-hidden="true" />
          Too little was observed about this company for the score to carry weight. Treat it as a
          prior, not a finding, and rely on the evidence sections below.
        </p>
      )}

      {data.model && (
        <details className="vs-details">
          <summary><Info size={11} aria-hidden="true" /> How this score was produced</summary>
          <dl className="vs-dl">
            <div><dt>Model</dt><dd>{data.model.family?.toUpperCase()} ensemble, {data.model.calibration} calibrated</dd></div>
            {/*
              The population has to be named. "1,560 companies with known
              outcomes" reads as though the model were validated on startups
              generally; it is Y Combinator alumni only, and the only
              genuinely out-of-sample holdout available contains zero B2B and
              zero Fintech companies.
            */}
            <div><dt>Trained on</dt><dd>{data.model.trained_n?.toLocaleString()} <strong>Y&nbsp;Combinator</strong> companies
              with recorded outcomes — not a general startup population</dd></div>
            <div><dt>Discrimination (cross-validated)</dt><dd>ROC-AUC {data.model.cv_roc_auc}
              {data.model.cv_roc_auc_ci95 && ` (95% CI ${data.model.cv_roc_auc_ci95[0]}–${data.model.cv_roc_auc_ci95[1]})`}</dd></div>
            {/*
              Reported next to the CV figure because they are different claims
              and the weaker one is the honest headline. See
              ml/eval/validation/out_of_sample_verified.json.
            */}
            <div><dt>Discrimination (held out)</dt><dd>ROC-AUC 0.636 (95% CI 0.562–0.702) on 261
              companies the model never saw. Measured on a holdout containing
              <strong> no B2B and no Fintech</strong> companies, so it does not
              establish performance in those sectors.</dd></div>
            <div><dt>Calibration error</dt><dd>{data.model.cv_ece} — a predicted 70% means roughly 70%</dd></div>
            {!!data.model.excluded_contaminated_features?.length && (
              <div>
                <dt>Excluded by design</dt>
                <dd>{data.model.excluded_contaminated_features.join(", ")} — these encode hindsight
                  and would inflate accuracy while misjudging early-stage companies</dd>
              </div>
            )}
          </dl>
          {data.caveat && <p className="vs-caveat">{data.caveat}</p>}
        </details>
      )}
    </section>
  );
}
