"""The content of a due-diligence report, once, in a format-neutral form.

`report_pdf.py` used to hold both *what goes in the report* and *how to draw it
in reportlab*, tangled together. Adding Word and Markdown export on top of that
would have meant three copies of the content decisions -- which sections
appear, in what order, what the caveat under the comparables table says -- and
three places to update when the report changes. In practice that is how export
formats drift until the PDF and the Word file disagree about what the analysis
found.

So the content lives here as a list of typed blocks, and each renderer
(`report_pdf`, `report_docx`, `report_markdown`) is a pure function from blocks
to bytes. Adding a fourth format means writing one renderer and changing
nothing about the content.

Block kinds, all plain dicts so they serialise and diff cleanly:

    {"kind": "title",    "text": str}
    {"kind": "meta",     "text": str}
    {"kind": "heading",  "text": str}
    {"kind": "text",     "text": str}          # may contain newlines
    {"kind": "bullets",  "items": [str]}
    {"kind": "table",    "header": [str], "rows": [[str]]}
    {"kind": "caveat",   "text": str}          # small print, must never be dropped

Every section is read with .get() and emitted only when it has content, which
is the same degrade-don't-crash contract every other reader of `sections` in
this codebase follows.
"""
from __future__ import annotations

from typing import Any

Block = dict[str, Any]

FOOTER_CAVEAT = (
    "Generated by VentureFlow AI. This report combines evidence-grounded LLM "
    "analysis with additional trained/rule-based signals where available; it is "
    "not a substitute for independent due diligence."
)


def _clean_list(items: Any) -> list[str]:
    if not isinstance(items, list):
        return []
    return [str(item) for item in items if item not in (None, "")]


def build_report_blocks(report: dict[str, Any], generated_on: str) -> list[Block]:
    """Format-neutral content for one report. Never raises on a missing section."""
    sections = report.get("sections", {}) or {}
    blocks: list[Block] = []

    company = report.get("company", "Unknown Company")
    blocks.append({"kind": "title", "text": "VentureFlow Due Diligence Report"})
    blocks.append({"kind": "meta", "text": f"{company} · Generated {generated_on}"})

    blocks.append({
        "kind": "table",
        "header": ["Overall Score", "Recommendation", "Risk Level"],
        "rows": [[
            f"{report.get('final_score', 0)}/100",
            str(report.get("recommendation", "NEEDS MORE DILIGENCE")),
            str(report.get("risk_level", "UNKNOWN")),
        ]],
    })

    blocks.append({"kind": "heading", "text": "Investment Memo"})
    blocks.append({"kind": "text", "text": sections.get("ai_analysis") or "No AI memo was generated."})

    claims = sections.get("claims") or {}
    if claims:
        blocks.append({"kind": "heading", "text": "Claim Verification"})
        blocks.append({"kind": "text", "text": (
            f"{claims.get('checked', 0)} claim(s) checked · "
            f"{claims.get('supported', 0)} supported · "
            f"{claims.get('refuted', 0)} refuted · "
            f"{claims.get('uncertain', 0)} uncertain"
        )})
        details = claims.get("details")
        if isinstance(details, list) and details:
            blocks.append({
                "kind": "table",
                "header": ["Claim", "Verdict", "Confidence"],
                "rows": [[
                    str(detail.get("claim", ""))[:160],
                    str(detail.get("verdict", "")),
                    f"{float(detail.get('confidence') or 0):.0%}",
                ] for detail in details[:8] if isinstance(detail, dict)],
            })

    for heading, key in (
        ("Key Concerns", "key_concerns"),
        ("Red Flags", "red_flags"),
        ("Positive Factors", "positive_factors"),
    ):
        blocks.append({"kind": "heading", "text": heading})
        blocks.append({"kind": "bullets", "items": _clean_list(report.get(key)) or ["None identified."]})

    # Founder background checks. Absent from the PDF until 23 Aug 2026 for the
    # same reason the Founder Analysis tab was empty: the agent never ran,
    # because nothing populated DiligenceRequest.founders.
    founder_checks = [
        check for check in (sections.get("founder_verification") or [])
        if isinstance(check, dict) and check.get("available")
    ]
    if founder_checks:
        blocks.append({"kind": "heading", "text": "Founder Background Checks"})
        blocks.append({
            "kind": "table",
            "header": ["Founder", "Assessment", "Confidence", "Evidence"],
            "rows": [[
                str(check.get("name", "")),
                str(check.get("assessment", "NOT_ENOUGH_INFO")),
                f"{float(check.get('confidence') or 0):.0%}",
                str(check.get("evidence_summary", ""))[:220],
            ] for check in founder_checks[:5]],
        })
        blocks.append({"kind": "caveat", "text": (
            "Public web evidence only. NOT_ENOUGH_INFO is the expected result for a "
            "founder with little public footprint and is not itself a negative signal."
        )})

    comparables = sections.get("market_comparables") or {}
    if comparables.get("available"):
        rows = [[
            str(comp.get("name", "")), str(comp.get("industry", "")), str(comp.get("stage", "")),
            str(comp.get("outcome", "")), f"{float(comp.get('similarity') or 0):.2f}",
        ] for comp in (comparables.get("comparables") or [])[:5]]
        if rows:
            blocks.append({"kind": "heading", "text": "Comparable Companies"})
            blocks.append({
                "kind": "table",
                "header": ["Company", "Industry", "Stage", "Outcome", "Similarity"],
                "rows": rows,
            })
            if comparables.get("caveat"):
                blocks.append({"kind": "caveat", "text": str(comparables["caveat"])})

    outcome_model = sections.get("ml_outcome_model") or {}
    if outcome_model.get("available"):
        blocks.append({"kind": "heading", "text": "Outcome Model Signal"})
        blocks.append({"kind": "text", "text": (
            f"Probability of survival/exit: "
            f"{float(outcome_model.get('probability_survives_or_exits') or 0):.0%} "
            f"({outcome_model.get('band', 'n/a')}) · "
            f"model test ROC-AUC {outcome_model.get('model_test_auc', 'n/a')}"
        )})
        if outcome_model.get("caveat"):
            blocks.append({"kind": "caveat", "text": str(outcome_model["caveat"])})

    technical_score = sections.get("technical_score") or {}
    if technical_score.get("available"):
        blocks.append({"kind": "heading", "text": "Technical/GitHub Score"})
        blocks.append({"kind": "text", "text": (
            f"{technical_score.get('score', 0)}/100 for {technical_score.get('repo', '')}"
        )})

    blocks.append({"kind": "caveat", "text": FOOTER_CAVEAT})
    return blocks
