"""The content of a due-diligence report, once, in a format-neutral form.

`report_pdf.py` used to hold both *what goes in the report* and *how to draw it
in reportlab*, tangled together. Adding Word and Markdown export on top of that
would have meant three copies of the content decisions -- which sections
appear, in what order, what the caveat under the comparables table says -- and
three places to update when the report changes. In practice that is how export
formats drift until the PDF and the Word file disagree about what the analysis
found.

So the content lives here as a list of typed blocks, and each renderer
(`report_pdf`, `report_docx`, `report_markdown`) is a pure function from blocks
to bytes. Adding a fourth format means writing one renderer and changing
nothing about the content.

Block kinds, all plain dicts so they serialise and diff cleanly:

    {"kind": "title",    "text": str}
    {"kind": "meta",     "text": str}
    {"kind": "heading",  "text": str}
    {"kind": "text",     "text": str}          # may contain newlines
    {"kind": "bullets",  "items": [str]}
    {"kind": "table",    "header": [str], "rows": [[str]]}
    {"kind": "subheading", "text": str}        # a heading inside the memo
    {"kind": "caveat",   "text": str}          # small print, must never be dropped

Inline `**bold**` survives in `text` and in bullet items. It is markup each
renderer resolves differently -- reportlab wants `<b>`, python-docx wants a
separate run, Markdown already speaks it -- so it is left in the block rather
than decided here.

Every section is read with .get() and emitted only when it has content, which
is the same degrade-don't-crash contract every other reader of `sections` in
this codebase follows.
"""
from __future__ import annotations

import re
from typing import Any

Block = dict[str, Any]

FOOTER_CAVEAT = (
    "Generated by VentureFlow AI. This report combines evidence-grounded LLM "
    "analysis with additional trained/rule-based signals where available; it is "
    "not a substitute for independent due diligence."
)


# ── The memo arrives as Markdown ───────────────────────────────────────────
#
# The model writes the investment memo in Markdown: `**1. EXECUTIVE SUMMARY**`
# headings, `- ` bullets, `---` rules and pipe tables. It used to be emitted as
# a single text block, so the reader got the asterisks and the pipes verbatim:
# a claim-verification table arrived as a wall of `| ... | ... |` lines in the
# PDF. The structure was already in the text; it only needed reading.

_RULE_LINE = re.compile(r"^\s*([-*_])\1{2,}\s*$")
_MD_HEADING = re.compile(r"^\s*#{1,6}\s+(.+?)\s*$")
# A line that is entirely bold is a heading, with or without a trailing colon:
# "**1. EXECUTIVE SUMMARY**", "**What drives the score:**".
_BOLD_LINE = re.compile(r"^\s*\*\*(.+?)\*\*\s*:?\s*$")
_BULLET_LINE = re.compile(r"^\s*[-*•]\s+(.+?)\s*$")
# The `|---|:--:|` row beneath a Markdown table header carries no content.
_TABLE_SEPARATOR = re.compile(r"^\s*\|?[\s:|-]+\|[\s:|-]*$")


def _table_cells(line: str) -> list[str]:
    parts = line.strip().split("|")
    if parts and not parts[0].strip():
        parts = parts[1:]
    if parts and not parts[-1].strip():
        parts = parts[:-1]
    return [cell.strip() for cell in parts]


def memo_blocks(memo: str) -> list[Block]:
    """The model's Markdown, as typed blocks. Never raises.

    Anything it cannot classify stays a paragraph, so a memo written as plain
    prose comes through unchanged rather than mangled.
    """
    lines = str(memo or "").replace("\r\n", "\n").split("\n")
    blocks: list[Block] = []
    paragraph: list[str] = []
    bullets: list[str] = []

    def flush_paragraph() -> None:
        if paragraph:
            text = "\n".join(paragraph).strip()
            if text:
                blocks.append({"kind": "text", "text": text})
            paragraph.clear()

    def flush_bullets() -> None:
        if bullets:
            blocks.append({"kind": "bullets", "items": list(bullets)})
            bullets.clear()

    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()

        if stripped.startswith("|") and stripped.count("|") >= 2:
            flush_paragraph()
            flush_bullets()
            rows: list[list[str]] = []
            while index < len(lines) and lines[index].strip().startswith("|"):
                if not _TABLE_SEPARATOR.match(lines[index]):
                    cells = _table_cells(lines[index])
                    if cells:
                        rows.append(cells)
                index += 1
            if rows:
                width = max(len(row) for row in rows)
                padded = [row + [""] * (width - len(row)) for row in rows]
                blocks.append({"kind": "table", "header": padded[0], "rows": padded[1:]})
            continue

        if not stripped or _RULE_LINE.match(stripped):
            flush_paragraph()
            flush_bullets()
            index += 1
            continue

        heading = _MD_HEADING.match(line) or _BOLD_LINE.match(line)
        if heading:
            flush_paragraph()
            flush_bullets()
            blocks.append({"kind": "subheading",
                           "text": heading.group(1).strip().strip("*").strip()})
            index += 1
            continue

        bullet = _BULLET_LINE.match(line)
        if bullet:
            flush_paragraph()
            bullets.append(bullet.group(1).strip())
            index += 1
            continue

        flush_bullets()
        paragraph.append(stripped)
        index += 1

    flush_paragraph()
    flush_bullets()
    return blocks


def _clean_list(items: Any) -> list[str]:
    if not isinstance(items, list):
        return []
    return [str(item) for item in items if item not in (None, "")]


def build_report_blocks(report: dict[str, Any], generated_on: str) -> list[Block]:
    """Format-neutral content for one report. Never raises on a missing section."""
    sections = report.get("sections", {}) or {}
    blocks: list[Block] = []

    company = report.get("company", "Unknown Company")
    blocks.append({"kind": "title", "text": "VentureFlow Due Diligence Report"})
    blocks.append({"kind": "meta", "text": f"{company} · Generated {generated_on}"})

    blocks.append({
        "kind": "table",
        # Flagged so a renderer can lead with the headline rather than treat it
        # as one more grid. A renderer that ignores the flag is still correct.
        "role": "summary",
        "header": ["Overall Score", "Recommendation", "Risk Level"],
        "rows": [[
            f"{report.get('final_score', 0)}/100",
            str(report.get("recommendation", "NEEDS MORE DILIGENCE")),
            str(report.get("risk_level", "UNKNOWN")),
        ]],
    })

    blocks.append({"kind": "heading", "text": "Investment Memo"})
    memo = sections.get("ai_analysis")
    blocks.extend(memo_blocks(memo) if memo
                  else [{"kind": "text", "text": "No AI memo was generated."}])

    claims = sections.get("claims") or {}
    if claims:
        blocks.append({"kind": "heading", "text": "Claim Verification"})
        blocks.append({"kind": "text", "text": (
            f"{claims.get('checked', 0)} claim(s) checked · "
            f"{claims.get('supported', 0)} supported · "
            f"{claims.get('refuted', 0)} refuted · "
            f"{claims.get('uncertain', 0)} uncertain"
        )})
        details = claims.get("details")
        if isinstance(details, list) and details:
            blocks.append({
                "kind": "table",
                "header": ["Claim", "Verdict", "Confidence"],
                "rows": [[
                    str(detail.get("claim", ""))[:160],
                    str(detail.get("verdict", "")),
                    f"{float(detail.get('confidence') or 0):.0%}",
                ] for detail in details[:8] if isinstance(detail, dict)],
            })

    for heading, key in (
        ("Key Concerns", "key_concerns"),
        ("Red Flags", "red_flags"),
        ("Positive Factors", "positive_factors"),
    ):
        blocks.append({"kind": "heading", "text": heading})
        blocks.append({"kind": "bullets", "items": _clean_list(report.get(key)) or ["None identified."]})

    # Founder background checks. Absent from the PDF until 23 Aug 2026 for the
    # same reason the Founder Analysis tab was empty: the agent never ran,
    # because nothing populated DiligenceRequest.founders.
    founder_checks = [
        check for check in (sections.get("founder_verification") or [])
        if isinstance(check, dict) and check.get("available")
    ]
    if founder_checks:
        blocks.append({"kind": "heading", "text": "Founder Background Checks"})
        blocks.append({
            "kind": "table",
            "header": ["Founder", "Assessment", "Confidence", "Evidence"],
            "rows": [[
                str(check.get("name", "")),
                str(check.get("assessment", "NOT_ENOUGH_INFO")),
                f"{float(check.get('confidence') or 0):.0%}",
                str(check.get("evidence_summary", ""))[:220],
            ] for check in founder_checks[:5]],
        })
        blocks.append({"kind": "caveat", "text": (
            "Public web evidence only. NOT_ENOUGH_INFO is the expected result for a "
            "founder with little public footprint and is not itself a negative signal."
        )})

    # What the headline number means -- the same text the UI shows beside it
    # (ml/score_context.py), so the PDF and the screen cannot describe one
    # score two different ways.
    context = sections.get("score_context") or {}
    if context.get("available"):
        blocks.append({"kind": "heading", "text": "What the Score Means"})
        blocks.append({"kind": "text", "text": str(context.get("measures", ""))})
        if context.get("band_reason"):
            blocks.append({"kind": "text", "text": str(context["band_reason"])})
        mix_sentence = (context.get("comparable_mix") or {}).get("sentence")
        if mix_sentence:
            blocks.append({"kind": "text", "text": str(mix_sentence)})
        if context.get("base_rate_note"):
            blocks.append({"kind": "caveat", "text": str(context["base_rate_note"])})
    comparables = sections.get("market_comparables") or {}
    if comparables.get("available"):
        rows = [[
            str(comp.get("name", "")), str(comp.get("industry", "")), str(comp.get("stage", "")),
            str(comp.get("outcome", "")), f"{float(comp.get('similarity') or 0):.2f}",
        ] for comp in (comparables.get("comparables") or [])[:5]]
        if rows:
            blocks.append({"kind": "heading", "text": "Comparable Companies"})
            blocks.append({
                "kind": "table",
                "header": ["Company", "Industry", "Stage", "Outcome", "Similarity"],
                "rows": rows,
            })
            if comparables.get("caveat"):
                blocks.append({"kind": "caveat", "text": str(comparables["caveat"])})

    outcome_model = sections.get("ml_outcome_model") or {}
    if outcome_model.get("available"):
        blocks.append({"kind": "heading", "text": "Outcome Model Signal"})
        blocks.append({"kind": "text", "text": (
            f"Probability of an exit (acquired or public) rather than a shutdown: "
            f"{float(outcome_model.get('probability_survives_or_exits') or 0):.0%} "
            f"({outcome_model.get('band', 'n/a')}) · "
            f"model test ROC-AUC {outcome_model.get('model_test_auc', 'n/a')}"
        )})
        if outcome_model.get("caveat"):
            blocks.append({"kind": "caveat", "text": str(outcome_model["caveat"])})

    technical_score = sections.get("technical_score") or {}
    if technical_score.get("available"):
        blocks.append({"kind": "heading", "text": "Technical/GitHub Score"})
        blocks.append({"kind": "text", "text": (
            f"{technical_score.get('score', 0)}/100 for {technical_score.get('repo', '')}"
        )})

    blocks.append({"kind": "caveat", "text": FOOTER_CAVEAT})
    return blocks
